### PR TITLE
Fix: adjust era offset in `PallasChainObserver` for correct display name

### LINKED ISSUE #2111: Cardano era in status page of aggregator is incorrect
## Why

The `/status` route returns an unexpected `Babagge` era when the Cardano node is running `Conway` on `testing-preview` and `testing-sanchonet`:
```json
{
  "epoch": 750,
  "cardano_era": "Babbage",
  "mithril_era": "pythagoras",
  "cardano_node_version": "10.1.2",
  "aggregator_node_version": "0.5.110+e2fa1e0",
  "protocol": {
    "k": 2422,
    "m": 20973,
    "phi_f": 0.2
  },
  "next_protocol": {
    "k": 2422,
    "m": 20973,
    "phi_f": 0.2
  },
  "total_signers": 3,
  "total_next_signers": 3,
  "total_stakes_signers": 28492690661,
  "total_next_stakes_signers": 28492690661,
  "total_cardano_spo": 315,
  "total_cardano_stake": 587868773564114
}
```
### Investigation

After investigation with `Pallas` developers, it appears that there is an offset of `1` which comes from the implementation of the Cardano node itself:
- The `Era` enum is a direct mapping of the cbor wrapper flag that is found in blocks via chain-sync.
- The era returned via local-state queries is different.
- One is the official era sequence and the other is the protocol version.

## What

Fix the era conversion in the Pallas chain observer to return the correct epoch

## How

- [x] Fix the conversion done by the Pallas chain observer: `Era::try_from(era + 1)`
- [x] Add a comment explaining that "The era value returned from the `queries_v16::get_current_era` has an offset of `-1` with the era value of the `pallas_traverse::Era` due to Cardano node implementation and it needs to be compensated to get the correct era display name.`

### PR DESCRIPTION
**Pull request by dlachaume**
## Content

This PR includes a fix for the retrieval of the Cardano era in the `PallasChainObserver` to ensure the correct era display name is returned. The offset is adjusted to align with the era mapping differences in the Cardano node implementation.

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [ ] CHANGELOG file is updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)

## Issue(s)

Closes #2111

### CODE REVIEW

File: mithril-common/src/chain_observer/pallas_observer.rs [hunk 1]
```diff
@@ -894,8 +898,8 @@ mod tests {
     }
 
     #[tokio::test]
-    async fn get_current_era() {
-        let socket_path = create_temp_dir("get_current_era_as_string").join("node.socket");
+    async fn get_adjusted_current_era() {
```
Comment (jpraynaud) [inline mithril-common/src/chain_observer/pallas_observer.rs:901]:
```suggestion
    async fn get_current_era() {
```

**Review by jpraynaud — APPROVED** [review]
LGTM :+1:

File: mithril-common/src/chain_observer/pallas_observer.rs (hunk 1 above)
Comment (dlachaume) [reply mithril-common/src/chain_observer/pallas_observer.rs]: Done ✅
