### PR TITLE
Fix: `CardanoDatabase` artifact identifier collisions

### LINKED ISSUE #2197: `CardanoDatabase` artifact identifiers have collisions
## Why
We have noticed that the `CardanoDatabase` artifact can have collisions on their identifiers. This happens when the same immutable file number is snapshot on two different epochs. This is also a source of flakiness in the CI.

## What
Replace the identifier of the `CardanoDatabase` artifact to a `hash` computed from the `merkle_root` and the `epoch`

## How

- [x] Implement a new `hash` identifier for the `CardanoDatabase` artifact
- [x] Update the HTTP routes
- [x] Update the OpenAPI specs

### PR DESCRIPTION
**Pull request by jpraynaud**
## Content

This PR includes a **fix to avoid collisions of the `CardanoDatabase` artifacts** when a snapshot is taken for the same immutable file number at two different epochs.

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested

## Issue(s)
Closes #2197

### CODE REVIEW

**Review by dlachaume — APPROVED** [review]
LGTM 👍

**Review by dlachaume — APPROVED** [review]

File: mithril-common/src/entities/cardano_database.rs [hunk 1]
```diff
@@ -106,6 +122,109 @@ pub struct ArtifactsLocations {
...
+                merkle_root: "mk-root-456".to_string(),
+                beacon: CardanoDbBeacon::new(123, 98),
+                ..dummy()
+            }
+            .compute_hash()
+        );
+    }
+
+    #[test]
+    fn compute_hash_returns_different_hash_with_different_beacon() {
```
Comment (sfauvel) [inline mithril-common/src/entities/cardano_database.rs:199]: Return different hash with different beacon epoch but return same hash with different immutable file.
We may create 2 tests to give them a more explicit name

**Review by sfauvel — APPROVED** [review]
LGTM

File: mithril-common/src/entities/cardano_database.rs (hunk 1 above)
Comment (jpraynaud) [reply mithril-common/src/entities/cardano_database.rs:199]: Done :+1:
