### PR TITLE
fix hanging critical error

### LINKED ISSUE #993: Aggregator does not exit on critical error
## Issue
On the `testing-preview` network, the aggregator did not exit when it received a critical error. The node was unabvailable until a manual restart was operated.

Here are the logs from the aggregator:
```
{"msg":"state machine: a critical error occurred: Critical error:'transiting SIGNING → READY: failed creating artifact'. Nested error: Some(\n    CreateArchiveError(\n        Os {\n            code: 2,\n            kind: NotFound,\n            message: \"No such file or directory\",\n        },\n    ),\n).","v":0,"name":"slog-rs","level":60,"time":"2023-06-16T11:14:32.298269004Z","hostname":"83cac7ae5269","pid":1}
{"msg":"A critical error occurred: Critical error:'transiting SIGNING → READY: failed creating artifact'. Nested error: Some(\n    CreateArchiveError(\n        Os {\n            code: 2,\n            kind: NotFound,\n            message: \"No such file or directory\",\n        },\n    ),\n).","v":0,"name":"slog-rs","level":60,"time":"2023-06-16T11:14:32.29833479Z","hostname":"83cac7ae5269","pid":1}
{"msg":"Event store is finishing...","v":0,"name":"slog-rs","level":30,"time":"2023-06-16T11:14:32.298769849Z","hostname":"83cac7ae5269","pid":1}
```

A first investigation shows that this part of the code is probably responsible for this behavior `mithril-aggregator/src/command_args.rs`:
```
info!("Event store is finishing...");
event_store_thread.await?;
println!("Services stopped, exiting.");
```
Apparently the event store did not stop.

### PR DESCRIPTION
**Pull request by ghubertpalo**
## Content

This PR includes...

## Pre-submit checklist

- Branch
  - [ ] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)

## Comments
None

## Issue(s)
Closes #993

### CODE REVIEW

File: mithril-aggregator/src/command_args.rs [hunk 1]
```diff
@@ -244,7 +244,7 @@ impl ServeCommand {
         let _ = shutdown_tx.send(());
 
         info!("Event store is finishing...");
-        event_store_thread.await?;
+        event_store_thread.await.unwrap();
```
Comment (jpraynaud) [inline mithril-aggregator/src/command_args.rs:247]: Is there any specific reason why you unwrapped here?

**Review by jpraynaud — APPROVED** [review]
LGTM :+1: 

Just a question about an unwrap

File: mithril-aggregator/src/command_args.rs (hunk 1 above)
Comment (ghubertpalo) [reply mithril-aggregator/src/command_args.rs:247]: yes, it should not change anything since the event store returns `Ok(())` I wanted to make it to fail as fast as possible in case of … whatever.
