### PR TITLE
List invalid or tampered immutable files in verify command

### LINKED ISSUE #2618: List the invalid/missing immutable files in the `verify` command in client CLI
## Why
We want to display the list of invalid or missing immutable files when the `verify` command of the client CLI is run. 

## What
Add a message explaining the range of immutable files which are verified by the command.
When the verification fails, an error message is displayed and explains which files are corrupted or missing.

## How

- [x] Add a `--start`, `--end` option to select a range to verify
- [x] Add a message detailing the exact range of immutable files being verified
- [x] For a given range:
  - [x] Detect missing immutable files except if `--allow-missing` option is set (fail-fast)
  - [x] If a valid Merkle proof can't be computed successfully:
    - [x] Verify that the digest file is valid (verify that the Merkle tree is certified by Mithril)
    - [x] Compute the list of computed digests that do not match the downloaded digests
- [x] Update examples crates
- [x] Update documentation

#### Step 1: verify the authenticity of the digest file (and return the Merkle tree + map of downloaded digests)
- [x] Download digests file
- [x] Compute Merkle tree
- [x] Verify the Merkle root of the Merkle tree matches the certificate

#### Step 2: attempt compute valid Merkle proof or the list of tampered immutable files
- [x] Compute local digests for the range (and list the missing files in the range)
- [x] Compute valid Merkle proof with Merkle tree:  
  - [x] Compute Merkle proof
  - [x] Verify Merkle proof is valid
- [x] If impossible to create the Merkle proof:
  - [x] Compute the difference between computed and downloaded digests (for the range)
- [x] If missing files or tampered files, return error with these lists 
   - [x] in CLI standard outout  and json output show count of missing and tampered files
   - [x] write a json file with all missing/tampered immutables
- [x] if more local immutable files than digests in downloaded json
   - [x]  return a list of "non verfied files"
   - [x] in CLI standard and json output show count of non verified files
   - [x] write a json of non verified files

### PR DESCRIPTION
**Pull request by turmelclem**
## Content

improve client library and CLI for verify command to list missing, tampered and/or non verifiable files
- verify command can now be use with a range
- a flag can be use (--allow-missing) to not throw error if immutable file is missing

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [ ] CHANGELOG file is updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] All check jobs of the CI have succeeded
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [x] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)
  - [ ] Add ADR blog post or Dev ADR entry (if relevant)
  - [x] No new TODOs introduced

## Issue(s)

Closes #2618

### CODE REVIEW

File: mithril-client/src/message.rs [hunk 1]
```diff
@@ -101,19 +200,92 @@ impl MessageBuilder {
...
+
+                return Ok(message);
+            }
+
+            let tampered_files = match proof_result {
+                Err(e) => {
+                    warn!(self.logger, "{MERKLE_PROOF_COMPUTATION_ERROR}: {e:}");
+                    verified_digests
+                        .list_immutable_files_not_verified(&computed_digest_entries)
+                        .tampered_files
```
[the remark this answers is not in the document]
Comment (turmelclem) [reply mithril-client/src/message.rs]: non_verifiable_files are now return with error and handled in client CLI

File: mithril-client-cli/src/commands/cardano_db/verify.rs [hunk 2]
```diff
@@ -102,45 +132,63 @@ impl CardanoDbVerifyCommand {
...
 
-        Self::log_verified_information(
-            db_dir,
-            &cardano_db_message.hash,
-            context.is_json_output_enabled(),
-        )?;
+        match message {
+            Err(e) => match e.downcast_ref::<ComputeCardanoDatabaseMessageError>() {
+                Some(ComputeCardanoDatabaseMessageError::ImmutableFilesVerification(lists)) => {
+                    // let missing_files = lists.missing;
```
Comment (dlachaume) [inline mithril-client-cli/src/commands/cardano_db/verify.rs]: You can remove this line.
```suggestion
```

File: mithril-client/src/message.rs [hunk 3]
```diff
@@ -1,26 +1,136 @@
 use anyhow::Context;
+#[cfg(feature = "fs")]
```
Comment (dlachaume) [inline mithril-client/src/message.rs]: Maybe we could reorganize the imports to merge the`#[cfg(feature = "fs")]` imports and improve readability?

File: mithril-client/src/message.rs [hunk 4]
```diff
@@ -1,26 +1,136 @@
...
     MithrilStakeDistribution, VerifiedCardanoTransactions,
     common::{ProtocolMessage, ProtocolMessagePartKey},
 };
 
+cfg_fs! {
+    const MERKLE_PROOF_COMPUTATION_ERROR:&str = "Merkle proof computation failed";
+
+    /// Type containing the lists of immutable files that are missing or tampered.
+    #[derive(Debug, PartialEq)]
+    pub struct ImmutableFilesLists {
```
Comment (dlachaume) [inline mithril-client/src/message.rs]: I'm looking for a better name to better reflect its business role.
Some suggestions: `ImmutableFileVerificationResult` or `ImmutableFileVerificationReport`.

File: mithril-client/src/message.rs [hunk 5]
```diff
@@ -1,26 +1,136 @@
...
+        ImmutableFilesVerification(ImmutableFilesLists),
+
+        /// Error related to the immutable files digests computation.
+        ImmutableFilesDigester(#[from] ImmutableDigesterError),
+
+        /// Error related to the Merkle proof verification.
+        MerkleProofVerification(#[source] MithrilError),
+
+        /// Error related to the immutable files range.
+        ImmutableFilesRange(#[source] MithrilError),
```
Comment (dlachaume) [inline mithril-client/src/message.rs]: Maybe names like `ImmutableFilesRangeConversion` or `ImmutableFilesRangeCreation` would better reflect its purpose?

File: mithril-client/src/message.rs (hunk 3 above)
Comment (turmelclem) [reply mithril-client/src/message.rs]: by merging it you suggest using a bloc with `cfg_fs! { ... } ` ?

File: mithril-client/src/message.rs (hunk 4 above)
Comment (turmelclem) [reply mithril-client/src/message.rs]: yes i think `ImmutableFileVerificationResult` is fine

File: examples/client-cardano-database-v2/src/main.rs [hunk 6]
```diff
@@ -98,19 +98,11 @@ async fn main() -> MithrilResult<()> {
         )
         .await?;
 
-    println!("Computing Cardano database Merkle proof...",);
-    let merkle_proof = client
+    println!("Downloading and verifying digests file authenticity...");
+    let verified_digest = client
```
Comment (Alenar) [inline examples/client-cardano-database-v2/src/main.rs]: Nitpick:
```suggestion
    let verified_digests = client
```

File: mithril-client/src/message.rs (hunk 3 above)
Comment (turmelclem) [reply mithril-client/src/message.rs]: imports have been reorganize using three blocks of `#[cfg(feature = "fs")] use { ... } `

File: mithril-client/src/cardano_database_client/proving.rs [hunk 7]
```diff
@@ -84,6 +92,52 @@ impl InternalArtifactProver {
         merkle_tree.compute_proof(&computed_digests)
     }
 
+    ///Download digests and verify its authenticity against the certificate.
```
Comment (jpraynaud) [inline mithril-client/src/cardano_database_client/proving.rs]:
```suggestion
/// Download digests and verify its authenticity against the certificate.
```

File: mithril-client/src/cardano_database_client/proving.rs [hunk 8]
```diff
@@ -298,6 +355,96 @@ mod tests {
...
+                    let digest = format!("digest-{i}-{name}");
+                    digests.insert(immutable_file, digest);
+                }
+            }
+
+            digests
+        }
+
+        #[tokio::test]
+        async fn download_and_verify_digest_should_return_digest_map_acording_to_beacon() {
```
Comment (jpraynaud) [inline mithril-client/src/cardano_database_client/proving.rs:396]:
```suggestion
async fn download_and_verify_digest_should_return_digest_map_according_to_beacon()
```

File: mithril-client/src/cardano_database_client/proving.rs [hunk 9]
```diff
@@ -27,7 +24,45 @@ use crate::{
...
+    /// A map of immutable file names to their corresponding verified digests.
+    pub digests: BTreeMap<ImmutableFileName, HexEncodedDigest>,
+    /// The Merkle tree built from the digests.
+    pub merkle_tree: MKTree<MKTreeStoreInMemory>,
+}
+
+#[derive(PartialEq, Debug)]
+pub(crate) struct ImmutableFilesNotVerified {
+    pub tampered_files: Vec<ImmutableFileName>,
+    pub non_verifiable_files: Vec<ImmutableFileName>,
```
Comment (jpraynaud) [inline mithril-client/src/cardano_database_client/proving.rs]: Comments are welcome here to explain the meaning of these fields.

File: mithril-client/src/cardano_database_client/proving.rs [hunk 10]
```diff
@@ -27,7 +24,45 @@ use crate::{
...
+
+        computed_digests.iter().for_each(|(immutable_file, digest)| {
+            let immutable_file_name_to_verify = immutable_file.filename.clone();
+            if let Some(verified_digest) = self.digests.get(&immutable_file_name_to_verify) {
+                if verified_digest != digest {
+                    tampered_files.push(immutable_file_name_to_verify);
+                }
+            } else {
+                non_verifiable_files.push(immutable_file_name_to_verify);
+            }
```
Comment (jpraynaud) [inline mithril-client/src/cardano_database_client/proving.rs]: You could have made that a bit more readable by using a match:
```suggestion
            match self.digests.get(&immutable_file_name_to_verify) {
               Some(verified_digest) if verified_digest != digest => {
                    tampered_files.push(immutable_file_name_to_verify);
               }
               None => {
                  non_verifiable_files.push(immutable_file_name_to_verify);
               }
            }
```

File: mithril-client-cli/src/commands/cardano_db/download/v2.rs [hunk 11]
```diff
@@ -124,22 +127,33 @@ impl PreparedCardanoDbV2Download {
...
+                "Can not download and verify digests file for cardano db snapshot with hash: '{}'",
+                self.hash
+            )
+        })?;
 
+        let options = ComputeCardanoDatabaseMessageOptions {
+            db_dir: restoration_options.db_dir.clone(),
+            immutable_file_range: restoration_options.immutable_file_range,
+            allow_missing: false,
+        };
```
Comment (Alenar) [inline mithril-client-cli/src/commands/cardano_db/download/v2.rs:149]: I wonder if this should be part of the client library directly to reduce the number of arguments of `compute_cardano_database_message`.

File: mithril-client/src/cardano_database_client/mod.rs [hunk 12]
```diff
@@ -4,7 +4,6 @@
 //!  - [get][CardanoDatabaseClient::get]: get a Cardano database data from its hash
 //!  - [list][CardanoDatabaseClient::list]: get the list of available Cardano database
 //!  - [download_unpack][CardanoDatabaseClient::download_unpack]: download and unpack a Cardano database snapshot for a given immutable files range
-//!  - [compute_merkle_proof][CardanoDatabaseClient::compute_merkle_proof]: compute a Merkle proof for a given Cardano database snapshot and a given immutable files range
```
Comment (Alenar) [inline mithril-client/src/cardano_database_client/mod.rs:7]: Should this be replaced with `download_and_verify_digests` ?

File: mithril-client/src/cardano_database_client/proving.rs [hunk 13]
```diff
@@ -27,7 +24,45 @@ use crate::{
...
+
+impl VerifiedDigests {
+    pub(crate) fn list_immutable_files_not_verified(
+        &self,
+        computed_digests: &BTreeMap<ImmutableFile, HexEncodedDigest>,
+    ) -> ImmutableFilesNotVerified {
+        let mut tampered_files = vec![];
+        let mut non_verifiable_files = vec![];
+
+        computed_digests.iter().for_each(|(immutable_file, digest)| {
```
Comment (Alenar) [inline mithril-client/src/cardano_database_client/proving.rs]: I think converting this to a straight `for (immutable_file, digest) in computed_digests` would be easier to read

File: mithril-client/src/message.rs [hunk 14]
```diff
@@ -1,25 +1,136 @@
...
+    }
+
+    /// Compute Cardano database message related errors.
+    #[derive(Error, Debug)]
+    pub enum ComputeCardanoDatabaseMessageError {
+        /// Error related to the verification of immutable files.
+        ImmutableFilesVerification(ImmutableVerificationResult),
+
+        /// Error related to the immutable files digests computation.
+        ImmutableFilesDigester(#[from] ImmutableDigesterError),
```
Comment (Alenar) [inline mithril-client/src/message.rs]: Something like `DigestsComputation` would avoid the direct reference to the `digester` which is only the tools that perform the operation (and would still be consistent with this error variant rustdoc).

File: mithril-client/src/message.rs (hunk 5 above)
Comment (turmelclem) [reply mithril-client/src/message.rs]: for example it will throw `ImmutableFilesRange(Invalid immutable file range: Range(20, 10))` , i think its quite understandable ?

File: mithril-client-cli/src/commands/cardano_db/download/v2.rs [hunk 15]
```diff
@@ -124,22 +124,41 @@ impl PreparedCardanoDbV2Download {
...
+        //     5,
+        //     &progress_printer,
+        //     &client,
+        //     &certificate,
+        //     &cardano_db_message,
+        //     &restoration_options.immutable_file_range,
+        //     &restoration_options.db_dir,
+        //     &verified_digests,
+        // )
+        // .await?;
```
Comment (jpraynaud) [inline mithril-client-cli/src/commands/cardano_db/download/v2.rs]: You forgot to remove this one.

**Review by Alenar — APPROVED** [review]
LGTM :racehorse:

File: mithril-client/src/message.rs [hunk 16]
```diff
@@ -101,19 +212,93 @@ impl MessageBuilder {
...
-                ProtocolMessagePartKey::CardanoDatabaseMerkleRoot,
-                merkle_proof.root().to_hex(),
-            );
+            certificate: &CertificateMessage,
+            cardano_database_snapshot: &CardanoDatabaseSnapshotMessage,
+            immutable_file_range: &ImmutableFileRange,
+            allow_missing: bool,
+            database_dir: &Path,
+            verified_digests: &VerifiedDigests,
+        ) -> Result<ProtocolMessage, ComputeCardanoDatabaseMessageError> {
```
Comment (jpraynaud) [inline mithril-client/src/message.rs:250]: IMO the proving part (Merkle proof computation) should be kept in the `proving` module. 
Also this function is too complex (too many inputs and lines).

File: mithril-client/src/cardano_database_client/proving.rs (hunk 10 above)
Comment (turmelclem) [reply mithril-client/src/cardano_database_client/proving.rs]: yes, but we will have to handle the equivalent of "else" case with  `_ => {}` 
```
match self.digests.get(&immutable_file_name_to_verify) {
    Some(verified_digest) if verified_digest != digest => {
        tampered_files.push(immutable_file_name_to_verify);
    }
    None => {
        non_verifiable_files.push(immutable_file_name_to_verify);
    }
    _ => {}
}
```
is it still more readable ? (I like both)

Comment (jpraynaud) [reply mithril-client/src/cardano_database_client/proving.rs]: IMO it is more readable :+1:

File: mithril-client/src/message.rs (hunk 16 above)
Comment (turmelclem) [reply mithril-client/src/message.rs:250]: as you see we now have added three new parameters since verified_digests are a dedicated step (that was previously done by compute_merkle_proof) so we need digests, range, and allow_missing flag. They may be reorganize in a struct ?

if we keep compute_merkle_proof in the proving.rs file has a exposed method for API, we will have to decide where to put the listing of missing immutable files and also the verification of the proof (tampered and non verifiable files)

see [explored possibilities here](https://miro.com/app/board/o9J_lKq5Szc=/?moveToWidget=3458764633859564360&cot=14)

File: mithril-client-cli/src/commands/cardano_db/shared_steps.rs [hunk 17]
```diff
@@ -47,45 +53,42 @@ pub fn immutable_file_range(
...
 
-    merkle_proof
-        .verify()
-        .with_context(|| "Merkle proof verification failed")?;
-
-    Ok(merkle_proof)
+    Ok(verified_digests)
 }
 
 /// Computes the Cardano database snapshot message using the provided certificate and Merkle proof.
```
Comment (turmelclem) [inline mithril-client-cli/src/commands/cardano_db/shared_steps.rs:72]: rework the function comment

File: mithril-client/src/message.rs (hunk 16 above)
Comment (turmelclem) [reply mithril-client/src/message.rs:250]: as discussed, we keep code as is, and it will be modified in the future

File: mithril-client-cli/src/commands/cardano_db/download/v2.rs (hunk 11 above)
Comment (turmelclem) [reply mithril-client-cli/src/commands/cardano_db/download/v2.rs:149]: will be kept as is but to be taken in consideration after, when it will be refactored

File: mithril-client/src/message.rs [hunk 18]
```diff
@@ -236,6 +236,9 @@ impl MessageBuilder {
         }
 
         /// Compute message for a Cardano database.
+        ///
+        /// This function first list missing immutables files (if `allow_missing` is false)
+        /// then compute the digests for the given range and finally compute the Merkle proof.
```
Comment (jpraynaud) [inline mithril-client/src/message.rs]:
```suggestion
        /// This function first lists missing immutables files (if `allow_missing` is false)
        /// then computes the digests for the given range and finally computes the Merkle proof.
```

**Review by jpraynaud — APPROVED** [review]
LGTM :+1:
