### PR TITLE
fix SQLite deadlocks

### LINKED ISSUE #517: Fix database dead locks in Aggregator
## Issue
We have noticed some database locks occurring on the GCP Aggregator which these error messages:
* `cannot start a transaction within a transaction`
* `database is locked`

⚠  The problem occurred after activating the `pruning` feature of the stores #516 

Here are the full logs:
```
mithril-aggregator_1                | {"msg":"STATE MACHINE: an error occurred: ","v":0,"name":"slog-rs","level":50,"time":"2022-09-20T14:44:11.436860471Z","hostname":"1db9e5f989b2","pid":1,"error":"StoreError(AdapterError(QueryError(Error { code: Some(1), message: Some(\"cannot start a transaction within a transaction\") })))"}
mithril-aggregator_1                | {"msg":"… Cycle finished, Sleeping for 60000 ms","v":0,"name":"slog-rs","level":30,"time":"2022-09-20T14:44:11.436936131Z","hostname":"1db9e5f989b2","pid":1}
mithril-aggregator_1                | {"msg":"⇄ HTTP SERVER: certificate_pending","v":0,"name":"slog-rs","level":20,"time":"2022-09-20T14:44:11.436978054Z","hostname":"1db9e5f989b2","pid":1}
mithril-aggregator_1                | {"msg":"certificate_pending::error","v":0,"name":"slog-rs","level":40,"time":"2022-09-20T14:44:11.437023811Z","hostname":"1db9e5f989b2","pid":1,"error":"AdapterError(ParsingDataError(Error { code: Some(5), message: Some(\"database is locked\") }))"}
mithril-aggregator_1                | {"msg":"⇄ HTTP SERVER: certificate_pending","v":0,"name":"slog-rs","level":20,"time":"2022-09-20T14:44:12.626648308Z","hostname":"1db9e5f989b2","pid":1}
mithril-aggregator_1                | {"msg":"certificate_pending::error","v":0,"name":"slog-rs","level":40,"time":"2022-09-20T14:44:12.626705143Z","hostname":"1db9e5f989b2","pid":1,"error":"AdapterError(ParsingDataError(Error { code: Some(5), message: Some(\"database is locked\") }))"}
``` 

## Workaround
Restart the container

### PR DESCRIPTION
**Pull request by ghubertpalo**
## Content

Applies to your base code, this patch will:

 - remove SQL explicit transaction by using `DELETE … RETURNING` SQL statements
 - apply a wait & retry strategy to deal with database locking mechanism

## Pre-submit checklist

- Branch
  - [ ] Tests are provided (if possible)
  - [X] Commit sequence broadly makes sense
  - [X] Key commits have useful messages
- PR
  - [X] No clippy warnings in the CI
  - [X] Self-reviewed the diff
  - [X] Useful pull request description
  - [X] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)

## Comments

For now, the wait & retry strategy has only been applied on READ statements (that wait for data). If new lock problems arise, it should be considered to also wait & retry for WRITE statements.

## Issue(s)

Closes #517

### CODE REVIEW

File: mithril-common/src/store/adapter/sqlite_adapter.rs [hunk 1]
```diff
@@ -108,11 +108,24 @@ where
...
+            // database is probably locked
+            // wait and retry strategy
+            retries = retries.filter(|v| v > &1).map(|v| v - 1);
+
+            if retries.is_none() {
+                return Err(result
+                    .map_err(|e| AdapterError::ParsingDataError(e.into()))
+                    .unwrap_err());
+            }
+            sleep(Duration::from_millis(50));
```
Comment (jpraynaud) [inline mithril-common/src/store/adapter/sqlite_adapter.rs:124]: You could maybe declare a variable for wait duration? 
Also, it would be nice to have exponential back-off retry strategy, WDYT?

BTW, is there any way to test the retries?

**Review by jpraynaud — COMMENTED** [review]
We miss the `SQLite` min version requirements in the doc :wink:

File: mithril-common/src/store/adapter/sqlite_adapter.rs (hunk 1 above)
Comment (ghubertpalo) [reply mithril-common/src/store/adapter/sqlite_adapter.rs:124]: - Yes for the constant 👍🏻  
 - IMHO it is unnecessary to apply complex strategies here since simple ones work
 - the best way to test is to make the end to end test to work flawlessly (which seems to be the case with that patch)

**Review by jpraynaud — APPROVED** [review]
LGTM :+1:
