### PR TITLE
Fix verbosity log levels

### LINKED ISSUE #1325: mithril-client verbosity not following usage menu
## Context & versions
When checking the help menu (usage) of mithril-client it states each additional `v` increases verbosity from WARNING, to INFO to DEBUG. However, in practice, it appears a single v produces INFO and two v's produce DEBUG level.

Mithril client is from release binaries 2337.0 - mithril-client 0.4.2+7d5a683.

## Steps to reproduce
  1. Run `mithril-client -h`
  2. Observe usage menu:
  3. `Verbosity level (-v=warning, -vv=info, -vvv=debug)`
  4. Run `mithril-client -v [...]`
  5. Observe INFO level messages
  6. Run `mithril-client -vv [...]`
  7. Observe DEBUG level messages

## Actual behavior
When running `mithril-client -vv [...]` the following can be observed:
```
Oct 30 16:01:49.508 DEBG Run Mode: dev                                                                                                                                                                             
Oct 30 16:01:49.508 DEBG Reading configuration file './config/dev.json'.                                                                                                                                           
Oct 30 16:01:49.508 DEBG New AggregatorHTTPClient created
Oct 30 16:01:49.508 DEBG New MithrilCertificateVerifier created                                          
Oct 30 16:01:49.508 DEBG Snapshot service: show.                                                                                                                                                                   
Oct 30 16:01:49.508 DEBG Snapshot service: list.                                                                                                                                                                   
Oct 30 16:01:49.508 DEBG GET url='https://aggregator.release-preprod.api.mithril.network/aggregator/artifact/snapshots'.                                                                                           
Oct 30 16:01:49.526 DEBG Prepare request with version: 0.1.11                                                                                                                                                      
Oct 30 16:01:50.427 DEBG GET url='https://aggregator.release-preprod.api.mithril.network/aggregator/artifact/snapshot/e9e0172b9b916e5a5432fac75f7187ba20c50426d70ed900e22a53aa7304b804'.                           
Oct 30 16:01:50.451 DEBG Prepare request with version: 0.1.11                                            
1/6 - Checking local disk info…                     
Oct 30 16:01:51.220 DEBG Snapshot service: download.                                                                                                                                                               
2/6 - Fetching the certificate's information…                                                                                                                                                                      
Oct 30 16:01:51.221 DEBG GET url='https://aggregator.release-preprod.api.mithril.network/aggregator/certificate/9a7718437af171c64adc8ebd93e1de78996c27a39e1cf3a782189c90afe9f841'.                                 
Oct 30 16:01:51.235 DEBG Prepare request with version: 0.1.11                                                                                                                                                      
3/6 - Verifying the certificate chain…                                                                   
⠁                                                                                                        
Oct 30 16:01:52.682 DEBG Verifying certificate, certificate_beacon: Beacon { network: "preprod", epoch: Epoch(103), immutable_file_number: 1987 }, certificate_previous_hash: a5cb43ffd7989e8a03235cedb7a30cd9b5c8e
fcbbabc0e5510b514187308b732, certificate_hash: 9a7718437af171c64adc8ebd93e1de78996c27a39e1cf3a782189c90afe9f841                                                                                                    
```

I'm unsure if the typo of **DEBG** vs. **DEBUG** is intentional and all logs are using a 4-character log level, I have not seen if it's WARN or WARNING in the logs. If it is not being limited to 4 characters then **DEBG** I presume is also a typo.

## Expected behavior
Using one v would enable WARNING and two V's would enable both WARNING and INFO levels, but not the DEBUG level.

### PR DESCRIPTION
**Pull request by dlachaumepalo**
## Content
This PR includes a fix for log levels problems that was raised in the issue #1325.

This consists of: 
- correctly adjust verbosity according to verbosity level (`-v`, `-vv`, `-vvv`)
- display `critical` level logs when parameter is absent

Changes have been implemented into:
- `mithril-client-cli`
- `mithril-aggregator`
- `mithril-signer`
- `mithril-relay`
- `mithril-test-lab` (`mithril-end-to-end` & `stress-test`)
 
## Pre-submit checklist

- Branch
  - [ ] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [x] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)

## Comments
Log level management has been added to the `mithril-end-to-end`, as it wasn't already included.

## Issue(s)
Closes #1325

### CODE REVIEW

File: mithril-aggregator/src/commands/mod.rs [hunk 1]
```diff
@@ -101,9 +101,10 @@ impl MainOpts {
     /// get log level from parameters
     pub fn log_level(&self) -> Level {
         match self.verbose {
-            0 => Level::Warning,
-            1 => Level::Info,
-            2 => Level::Debug,
+            0 => Level::Critical,
```
Comment (jpraynaud) [inline mithril-aggregator/src/commands/mod.rs:104]: It should probably `Error` instead?
```suggestion
            0 => Level::Error,
```

**Review by jpraynaud — APPROVED** [review]
LGTM :+1:

**Review by ghubertpalo — APPROVED** [review]
