### PR TITLE
retry when artifact creation failed

### LINKED ISSUE #984: Add a retry mechanism for artifact creation in aggregator
## Issue
There is no retry mechanism when the artifact creation fails in the aggregator. 
We could implement it with:
- a retry mechanism in the signed entity service
- a proper detection of the artifact creation error and a new transition of the state machine from `SIGNING` to `READY`
- a panic and having the aggregator restart (as in fix for #953)

# Related issues
#953

### PR DESCRIPTION
**Pull request by ghubertpalo**
## Content
This PR makes the aggregator retry when artifact creation fails. If the artifact creation still fails, the state machine is reset.

## Pre-submit checklist

- Branch
  - [X] Tests are provided (if possible)
  - [ ] Crates versions are updated (if relevant)
  - [X] Commit sequence broadly makes sense
  - [X] Key commits have useful messages
- PR
  - [X] No clippy warnings in the CI
  - [X] Self-reviewed the diff
  - [X] Useful pull request description
  - [X] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)

## Comments
None

## Issue(s)
Closes #984

### CODE REVIEW

File: mithril-aggregator/src/runtime/runner.rs [hunk 1]
```diff
@@ -211,9 +211,11 @@ impl AggregatorRunnerTrait for AggregatorRunner {
                     "RUNNER: get_current_non_certified_open_message_for_signed_entity_type: no open message found, a new one will be created";
                     "signed_entity_type" => ?signed_entity_type
                 );
-                // In order to fix flakiness in the end to end tests, we are compelled to update the beacon (of the multi-signer)
-                // This avoids the computation of the next AVK on the wrong epoch (in 'compute_protocol_message')
-                // TODO: remove 'current_beacon' from the multi-signer state which will avoid this fix
+                // In order to fix flakiness in the end to end tests, we are
+                // compelled to update the beacon (of the multi-signer) This
+                // avoids the computation of the next AVK on the wrong epoch (in
+                // 'compute_protocol_message') TODO: remove 'current_beacon'
```
Comment (Alenar) [inline mithril-aggregator/src/runtime/runner.rs:217]: The `todo` should start on a new line

File: mithril-aggregator/src/runtime/state_machine.rs [hunk 2]
```diff
@@ -281,22 +307,26 @@ impl AggregatorRuntime {
...
-        // TODO: Implement a graceful retry mechanism for artifact creation and label open messages with `is_artifact_created` (to keep track of certified but without artifacts open messages)
-        self.runner.drop_pending_certificate().await.map_err(|e| {
-            RuntimeError::critical(
-                "transiting SIGNING → READY: failed dropping pending certificate",
-                Some(e),
-            )
-        })?;
+        // Every error raised below this comment must be raised to critical in
+        // order to trigger an aggregator restart which will avoid a dead loop
+        // in the state machine TODO: Implement a graceful retry mechanism for
```
Comment (Alenar) [inline mithril-aggregator/src/runtime/state_machine.rs:312]: The `todo` should start on a new line

File: mithril-aggregator/src/signed_entity_service.rs [hunk 3]
```diff
@@ -120,9 +120,23 @@ impl SignedEntityService for MithrilSignedEntityService {
...
+            match self
+                .compute_artifact(signed_entity_type.clone(), certificate)
+                .await
+            {
+                Err(e) => {
+                    if remaining_retries == 0 {
+                        break Err(e);
+                    }
+                }
+                Ok(a) => break Ok(a),
```
Comment (Alenar) [inline mithril-aggregator/src/signed_entity_service.rs:136]: For readability can you write `artifact` instead of `a` (and `err`/`error` instead of `e`) ?

File: mithril-aggregator/src/runtime/state_machine.rs [hunk 4]
```diff
@@ -281,22 +307,26 @@ impl AggregatorRuntime {
...
-        // Every error raised below this comment must be raised to critical in order to trigger an aggregator restart which will avoid a dead loop in the state machine
-        // TODO: Implement a graceful retry mechanism for artifact creation and label open messages with `is_artifact_created` (to keep track of certified but without artifacts open messages)
-        self.runner.drop_pending_certificate().await.map_err(|e| {
-            RuntimeError::critical(
-                "transiting SIGNING → READY: failed dropping pending certificate",
-                Some(e),
-            )
-        })?;
+        // Every error raised below this comment must be raised to critical in
+        // order to trigger an aggregator restart which will avoid a dead loop
```
Comment (jpraynaud) [inline mithril-aggregator/src/runtime/state_machine.rs:311]:
```suggestion
        // Every error raised below this comment must trigger a re-initialization
        // of the state mahcine which will avoid a dead loop
```

File: mithril-aggregator/src/runtime/state_machine.rs (hunk 2 above)
Comment (jpraynaud) [reply mithril-aggregator/src/runtime/state_machine.rs:312]: The `TODO` part can be removed as a retry mechanism is now implemented in the signed entity service

File: mithril-aggregator/src/runtime/state_machine.rs [hunk 5]
```diff
@@ -281,22 +307,26 @@ impl AggregatorRuntime {
...
         self.runner
             .create_artifact(&state.open_message.signed_entity_type, &certificate)
             .await
-            .map_err(|e| {
-                RuntimeError::critical(
-                    "transiting SIGNING → READY: failed creating artifact",
-                    Some(e),
-                )
+            .map_err(|e| RuntimeError::ReInit {
+                message: "transiting SIGNING → READY: failed to create artifact. Retrying…"
```
Comment (jpraynaud) [inline mithril-aggregator/src/runtime/state_machine.rs:327]: The retry likely occurred in the `create_artifact` function. Now the state machine will be re-initialized and there won't be any more retry on this artifact:
```suggestion
                message: "transiting SIGNING → READY: failed to create artifact"
```

**Review by jpraynaud — APPROVED** [review]
LGTM :+1: 

Except for few typos that need to be fixed before merging

**Review by Alenar — APPROVED** [review]
