### PR TITLE
test(halo2_ivc): add Layer B State tests

### LINKED ISSUE #3191: Add data encoding and state transition tests for recursive SNARK circuit prototype
## Why                     

The IVC circuit prototype needs regression protection before larger refactoring. Data encoding invariants and state transition rules form the foundation of the certificate chain: if a preimage layout drifts, a byte offset shifts, or a linkage rule is violated, every layer above silently produces wrong proofs. Locking these properties early with cheap, stable tests gives fast feedback in CI and prevents subtle breakage from propagating.
                                                                                                                                                                                                                                                                                                  
## What                    

Implement **Layer A** and **Layer B** of #3124: add unit tests and focused integration tests that validate deterministic data rules (encoding, serialization, offsets) and certificate chain transition semantics (linkage, epoch handling, genesis behavior).                                  
   
## How                                                                                                                                                                                                                                                                                          
                             
- [ ] Implement **Layer A (Data and encoding invariants)**                                                                                                                                                                                                                                      
  - [ ] Add tests for protocol message preimage layout
  - [ ] Add tests for byte offsets used by the circuit                                                                                                                                                                                                                                          
  - [ ] Add tests for state public input formatting
  - [ ] Add tests for accumulator serialization and deserialization round-trips
  - [ ] Add tests for proof and verifying key serialization round-trips                                                                                                                                                                                                                         
- [ ] Implement **Layer B (State transition rules)**
  - [ ] Add tests for genesis vs non-genesis behavior                                                                                                                                                                                                                                           
  - [ ] Add tests for same-epoch vs next-epoch transitions
  - [ ] Add tests for linkage of current Merkle root                                                                                                                                                                                                                                            
  - [ ] Add tests for linkage of next Merkle root
  - [ ] Add tests for linkage of protocol parameters                                                                                                                                                                                                                                            
  - [ ] Add tests for linkage of current epoch
  - [ ] Add tests for consistency between preimage and resulting state                                                                                                                                                                                                                          
- [ ] Ensure all Layer A and Layer B tests run in the fast CI tier

### PR DESCRIPTION
**Pull request by hjeljeli32**
## Content

This PR completes Layer B of the `halo2_ivc` test plan, covering state transition rule tests for the recursive IVC circuit.

It adds:
- positive transition tests verifying that stored Blake2b proofs accept correct public inputs for each transition type: genesis, same-epoch, and next-epoch
- negative transition tests: fast asset-based verifier checks confirming that tampered public inputs are rejected across all 7 state fields for each of the three transition types
- negative transition tests: slow `MockProver`-based checks confirming that the circuit enforces in-circuit linkage rules for Merkle root, protocol params, current epoch, and the `msg = Blake2b(msg_preimage)` hash constraint

It also extends the shared test infrastructure with two new committed binary assets (`genesis_step_output.bin`, `same_epoch_step_output.bin`), new generator functions for same-epoch and next-epoch steps, and a general clean-up of the test helpers to improve readibility and consistency.

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [x] CHANGELOG file is updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] All check jobs of the CI have succeeded
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [x] Update README file (if relevant)

## Comments

Closes https://github.com/input-output-hk/mithril/issues/3191

### CODE REVIEW

File: mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs [hunk 1]
```diff
@@ -488,3 +486,262 @@ pub(crate) fn generate_recursive_step_output_asset(
...
+    );
+
+    println!(
+        "generate_same_epoch_step_output: loading chain state <- {}",
+        paths.recursive_chain_state.display()
+    );
+    let chain_state = load_recursive_chain_state_asset(&paths.recursive_chain_state)
+        .expect("failed to load recursive_chain_state asset");
+
+    let mut rng = OsRng;
```
Comment (jpraynaud) [inline mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs:606]: We probably want to use deterministic RNG in tests?

File: mithril-stm/src/circuits/halo2_ivc/tests/common/helpers.rs [hunk 2]
```diff
@@ -192,6 +201,40 @@ pub(crate) fn prepare_stored_step_certificate_accumulator(
     certificate_accumulator
 }
 
+/// Builds an `IvcCircuit` wired for MockProver-based negative tests.
+///
+/// All negative tests pass empty certificate-proof / accumulator vecs because
+/// MockProver checks algebraic constraints without running the IPA/KZG prover.
+pub(crate) fn build_mock_prover_circuit(
```
Comment (jpraynaud) [inline mithril-stm/src/circuits/halo2_ivc/tests/common/helpers.rs]: Maybe the function name should reflect the fact that is is only for MockProver based negative tests?

File: mithril-stm/src/circuits/halo2_ivc/tests/encoding/negative.rs
Comment (jpraynaud) [inline mithril-stm/src/circuits/halo2_ivc/tests/encoding/negative.rs:1]: Can you make the modifications to separate slow tests from fast ones?

File: mithril-stm/src/circuits/halo2_ivc/tests/transitions/negative.rs
Comment (jpraynaud) [inline mithril-stm/src/circuits/halo2_ivc/tests/transitions/negative.rs:1]: This file is very long, maybe you can split it in sub-modules that represent genesis, current and next epochs tests?

File: mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs (hunk 1 above)
Comment (hjeljeli32) [reply mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs:606]: @jpraynaud 
The setup (KZG params, keys, Merkle tree, state values) already uses ChaCha20Rng for reproducibility. But, proof generation intentionally needs 0sRng: If I remember well ZK proofs require it for blinding factors. In `ivc_e2e.rs` that we copied from the prototype, we can see the commented-out ChaCha20Rng line and that 0sRng was intentionally used.

File: mithril-stm/src/circuits/halo2_ivc/tests/transitions/negative.rs
Comment (hjeljeli32) [reply mithril-stm/src/circuits/halo2_ivc/tests/transitions/negative.rs:1]: @jpraynaud 

In the commit you reviewed, this file was 1000+ lines..Since then, I refactored it using closure-based helpers, which made it ~445 lines with clear section comments separating genesis, same-epoch, and next-epoch tests. Does this address your concern, or would you still like the sub-module split?

Comment (jpraynaud) [reply mithril-stm/src/circuits/halo2_ivc/tests/transitions/negative.rs:1]: Thanks @hjeljeli32. Can you group tests under modules (which would have their own `slow` sub module) in this `negative.rs` instead of using comments to do the separation?

**Review by jpraynaud — APPROVED** [review]
LGTM 👍

File: .github/workflows/scripts/filter-slow-tests.sh [hunk 3]
```diff
@@ -89,7 +89,8 @@ readonly COMMIT_REF=${COMMIT_REF:-"origin/main"} ALLOW_ALL
 
 readonly -a SLOW_MITHRIL_STM_TESTS=(
   "mithril-stm/src/#protocol::aggregate_signature::"
-  "mithril-stm/src/circuits/halo2#circuits::halo2::"
+  "mithril-stm/src/circuits/halo2/#circuits::halo2::"
```
Comment (damrobi) [inline .github/workflows/scripts/filter-slow-tests.sh:92]: I'm not sure the `/` is needed here but maybe it is.

File: mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs [hunk 4]
```diff
@@ -487,6 +487,227 @@ pub(crate) fn generate_recursive_step_output_asset(
...
+        proof_start.elapsed()
+    );
+
+    println!(
+        "generate_genesis_step_output: writing asset -> {}",
+        paths.genesis_step_output.display()
+    );
+    let asset = RecursiveStepOutputAsset {
+        proof,
+        next_accumulator,
```
Comment (damrobi) [inline mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs:563]: Not so much a comment as a question, here `next_accumulator` is the trivial accumulator, correct? That is what we want after the genesis step? Or is it because we generated a blake2b proof that cannot be accumulate further?

File: mithril-stm/src/circuits/halo2_ivc/tests/transitions/positive.rs [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    let dual_msm = verify_and_prepare_blake2b_recursive_proof(
+        &verification_context.recursive_verifying_key,
+        &step_output.proof,
+        &public_inputs,
+    );
+
+    assert!(
+        dual_msm.check(&verification_context.verifier_params),
+        "{acceptance_message}"
+    );
```
Comment (damrobi) [inline mithril-stm/src/circuits/halo2_ivc/tests/transitions/positive.rs:46]: Maybe it's not the goal of this test but shouldn't we also verify the accumulator in addition to the proof? The `step_output.next_accumulator`?

File: mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs [hunk 6]
```diff
@@ -487,6 +487,227 @@ pub(crate) fn generate_recursive_step_output_asset(
...
+    let combined_fixed_base_names = combined_fixed_bases.keys().cloned().collect::<Vec<_>>();
+    let recursive_proving_key = build_recursive_proving_key(&context);
+    let global = build_recursive_global(
+        setup,
+        &context.certificate_verifying_key,
+        &context.recursive_verifying_key,
+    );
+
+    let genesis_witness = build_genesis_base_case_witness(setup);
+    let genesis_next_state = build_genesis_base_case_next_state(setup, 5u64);
```
Comment (curiecrypt) [inline mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs]: We could use `GENESIS_EPOCH` here instead of hardcoded `5u64`?

File: .github/workflows/scripts/filter-slow-tests.sh [hunk 7]
```diff
@@ -89,7 +89,8 @@ readonly COMMIT_REF=${COMMIT_REF:-"origin/main"} ALLOW_ALL
...
+  "mithril-stm/src/circuits/halo2_ivc#circuits::halo2_ivc::"
```
Comment (curiecrypt) [inline .github/workflows/scripts/filter-slow-tests.sh]:
```suggestion
  "mithril-stm/src/circuits/halo2_ivc/#circuits::halo2_ivc::"
```

**Review by damrobi — APPROVED** [review]
LGTM overall
I have a question regarding the verification of accumulators as I think I may have missed where it happens in the tests

File: mithril-stm/src/circuits/halo2_ivc/tests/golden/README.md [hunk 8]
```diff
@@ -30,32 +30,21 @@ git restore mithril-stm/src/circuits/halo2_ivc/tests/assets
...
+- `verification_context.bin` — static verifier-side context (verifying key, global inputs, fixed bases, SRS)
+- `recursive_chain_state.bin` — chain checkpoint after several recursive steps
+- `genesis_step_output.bin` — output of the genesis base-case step
+- `same_epoch_step_output.bin` — output of a same-epoch recursive step
+- `recursive_step_output.bin` — output of a next-epoch recursive step
 
 ## Dependency Order
 
-The assets have a simple dependency chain:
+Assets 1–3 are independent. Assets 4 and 5 both require asset 3 first:
```
Comment (curiecrypt) [inline mithril-stm/src/circuits/halo2_ivc/tests/golden/README.md]: nit: Dependency Order bullets explicitly state the dependency for assets 4 and 5 but leave assets 1-3 unmarked, which can read as if asset 3 has hidden dependencies.

**Review by curiecrypt — APPROVED** [review]
Just a few minor comments...
LGTM 👍

File: .github/workflows/scripts/filter-slow-tests.sh (hunk 3 above)
Comment (hjeljeli32) [reply .github/workflows/scripts/filter-slow-tests.sh:92]: Hi @damrobi , the / is intentional. Without it, mithril-stm/src/circuits/halo2 would match mithril-stm/src/circuits/halo2_ivc/... as a plain substring. Adding the trailing slash scopes it strictly to files under halo2/ and prevents halo2 slow tests from triggering on halo2_ivc file changes.

**Comment by hjeljeli32** [comment]
Hi @damrobi 
Great question about the accumulators, I will share my opinion here:

> [mithril-stm/src/circuits/halo2_ivc/tests/common/generators/asset_generation.rs](https://github.com/input-output-hk/mithril/pull/3229/files/f8424e38fa4cb95755c9e7662aa1aed5634e40de#diff-5e5a531a1585960ce449c4332a2c916e65db0e631931ed8be0a52004700beb36)
>     );
>     let asset = RecursiveStepOutputAsset {
>         proof,
>         next_accumulator,
> Member
> @[damrobi](https://github.com/damrobi)
> damrobi
> [9 hours ago](https://github.com/input-output-hk/mithril/pull/3229#discussion_r3161512307)
> Not so much a comment as a question, here next_accumulator is the trivial accumulator, correct? That is what we want after the genesis step? Or is it because we generated a blake2b proof that cannot be accumulate further?

 yes next_accumulator is the trivial accumulator at genesis. At the genesis step there is no certificate proof and no previous IVC proof to fold, so nothing is accumulated and the trivial accumulator is the correct output. In a normal non-genesis step, the previous step's Poseidon proof and the certificate proof are folded together into a non-trivial accumulator. The Blake2b proof generated here is the final verifier-facing proof, not something that enters the folding scheme.

>  [mithril-stm/src/circuits/halo2_ivc/tests/transitions/positive.rs](https://github.com/input-output-hk/mithril/pull/3229/files/f8424e38fa4cb95755c9e7662aa1aed5634e40de#diff-73854c705d27fa000feedaf8d6c5352e65e81a2acc83e63a274f5d2c64d026ab)
> Comment on lines +43 to +46
>     assert!(
>         dual_msm.check(&verification_context.verifier_params),
>         "{acceptance_message}"
>     );
> Member
> @[damrobi](https://github.com/damrobi)
> damrobi
> [9 hours ago](https://github.com/input-output-hk/mithril/pull/3229#discussion_r3161710895)
> Maybe it's not the goal of this test but shouldn't we also verify the accumulator in addition to the proof? The step_output.next_accumulator?

Good point. The accumulator check is technically possible here. I deliberately scoped these transition tests to proof verification only for now. The genesis accumulator is trivial so there's nothing meaningful to check, and the next-epoch case is already covered by `recursive_step_output_asset_proof_and_accumulator_are_valid` in the golden layer. The full off-circuit accumulator validation chain across steps is planned for Layer C2. Is it okay?
