### PR TITLE
fix:  snapshot converter breaking change since cardano version 10.6.2

### LINKED ISSUE #3010: Fix `snapshot-converter` breaking change in `10.6.2`
## Why
The `snapshot-converter` in the Cardano `10.6.2` has introduced breaking changes in the command line which prevents from converting new ledger state snapshot to different UTxO flavor in the `tools utxo-hd` of the client.

## What
Support multiple versions of the `snapshot-converter` command line interface.

## How

- [ ] Fix the [Mithril Client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) to support the Cardano node version of the snapshot in the `mithril-client tools utxo-hd` command (see this [branch](https://github.com/input-output-hk/mithril/compare/main...refs/heads/jpraynaud/2790-fix-client-multi-platform-workflow))
- [ ] Update the `mithril-client tools utxo-hd` command to support multiple command line syntax for the underlying `snapshot-converter` CLI
- [ ] Include the `mithril-client tools utxo-hd` command in the end to end test?

### PR DESCRIPTION
**Pull request by turmelclem**
## Content

This PR includes modifications on Mithril-client-cli : 
 - handling the new breaking change Snapshot-converter command format introduced in Cardano node 10.6.2
 - ensure retro-compatibility with previous command format for Cardano node version bellow 10.6.2
 - reject using snapshot converter with Utx0 HD Flavor Legacy and Cardano node version >=10.6.2 or "latest" since it not supported anymore

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [ ] Crates versions are updated (if relevant)
  - [ ] CHANGELOG file is updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] All check jobs of the CI have succeeded
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested
- Documentation
  - [ ] Update README file (if relevant)
  - [ ] Update documentation website (if relevant)
  - [ ] Add dev blog post (if relevant)
  - [ ] Add ADR blog post or Dev ADR entry (if relevant)
  - [x] No new TODOs introduced

## Issue(s)

Closes #3010

### CODE REVIEW

File: mithril-client-cli/src/commands/tools/utxo_hd/snapshot_converter.rs [hunk 1]
```diff
@@ -106,38 +107,92 @@ impl TryFrom<CardanoNetwork> for CardanoNetworkCliArg {
...
+}
+
+struct SnapshotConverterBinNew {
+    config: SnapshotConverterConfig,
+}
+
+enum SnapshotConverterEnum {
+    New(SnapshotConverterBinNew),
+    Old(SnapshotConverterBin),
+}
```
Comment (jpraynaud) [inline mithril-client-cli/src/commands/tools/utxo_hd/snapshot_converter.rs]: This would probably be more simple and readable:

```suggestion
enum SnapshotConverterBin {
    Up_to_10_5(SnapshotConverterConfig),
    From_10_6(SnapshotConverterConfig),
}
```

Also you could call the `convert` directly on the new `SnapshotConverterConfig` enum and match on the variant to create the command line.

File: .github/workflows/test-client.yml [hunk 2]
```diff
@@ -306,14 +307,21 @@ jobs:
...
             UTXO_HD_FLAVOR="LMDB"
           elif [[ ${LEDGER_BACKEND,,} == "legacy" ]]; then
             UTXO_HD_FLAVOR="Legacy"
           fi
 
+          if [[ ${LEDGER_BACKEND,,} == "legacy" ]] && \
+          [[ "$(printf '%s\n' "10.6.2" "$CARDANO_VERSION" | sort -V | head -n1)" == "10.6.2" ]]; then
+            echo "Skipping snapshot-converter: Legacy UTXO HD Flavor not supported for Cardano version >= 10.6.2"
+            exit 0
+          fi
```
Comment (Alenar) [inline .github/workflows/test-client.yml]: I think that removing all together the `legacy` case is more simple (and future proof)
```suggestion
```

File: mithril-client-cli/src/commands/tools/utxo_hd/snapshot_converter.rs [hunk 3]
```diff
@@ -168,43 +153,53 @@ impl SnapshotConverter for SnapshotConverterBin {
...
+    input_path: &Path,
+    output_path: &Path,
+    cfg: SnapshotConverterConfig,
+) -> Command {
+    let mut command = Command::new(cfg.converter_bin);
+
+    command
+        .arg("--mem-in")
+        .arg(input_path)
+        .arg("--lmdb-out")
```
Comment (jpraynaud) [inline mithril-client-cli/src/commands/tools/utxo_hd/snapshot_converter.rs]: This should be computed from `cfg.utxo_hd_flavor.to_string()`
