### PR TITLE
Fix Conway transactions parsing

### LINKED ISSUE #1577: Some transactions are not signed in `testing-sanchonet`
## Why
We have noticed that some transactions are not signed on `testing-sanchonet` whereas they were created recently, such as [5112f1570962ad84f01e4d323f16f3559f7fefd124ca266e8863344580f092f9](https://sancho.cexplorer.io/tx/5112f1570962ad84f01e4d323f16f3559f7fefd124ca266e8863344580f092f9)

## What
After investigating the logs of the aggregator on the `testing-sanchonet` it appears that there are some parsing issue remaining on the recently produced blocks.

Here is a log extract from a Mithril node running a pallas-hardano parser:
[parse-errors-tx-sanchonet-pallas-hardano.logs.txt](https://github.com/txpipe/pallas/files/14649375/parse-errors-tx-sanchonet-pallas-hardano.logs.txt)

The errors are due to `Invalid CBOR structure` witth several causes (at least the following ones):
- `unexpected type null at position XXX: expected array`
- `decode error: invalid variant for script enum`
- `unexpected type tag at position XXX: expected array`

## How

- [x] File a bug on Pallas repository
- [x] Update Pallas dependency once a new version is released
- [ ] Make sure the aggregator is not producing parsing errors on `testing-sanchonet`

## Related Issue
#1537

### PR DESCRIPTION
**Pull request by jpraynaud**
## Content
This PR includes a fix to the Conway transactions parsing which failed for some blocks with the previous version of `pallas` (bumped from `0.24.0` to `0.25.0`). Also re-activated the stop on error in the Cardano transaction parser.

## Pre-submit checklist

- Branch
  - [x] Crates versions are updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] No clippy warnings in the CI
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested

## Issue(s)
Closes #1577

### CODE REVIEW

File: mithril-aggregator/src/dependency_injection/builder.rs [hunk 1]
```diff
@@ -742,7 +742,7 @@ impl DependenciesBuilder {
 
     async fn build_transaction_parser(&mut self) -> Result<Arc<dyn TransactionParser>> {
         // TODO: 'allow_unparsable_block' parameter should be configurable and its default value set to false
```
Comment (Alenar) [inline mithril-aggregator/src/dependency_injection/builder.rs:744]: The comment should be updated since the default value is what's expected :).

File: mithril-signer/src/runtime/signer_services.rs [hunk 2]
```diff
@@ -267,7 +267,7 @@ impl<'a> ServiceBuilder for ProductionServiceBuilder<'a> {
         let mithril_stake_distribution_signable_builder =
             Arc::new(MithrilStakeDistributionSignableBuilder::default());
         // TODO: 'allow_unparsable_block' parameter should be configurable and its default value set to false
```
Comment (Alenar) [inline mithril-signer/src/runtime/signer_services.rs:269]: The comment should be updated since the default value is what's expected :).

**Review by Alenar — APPROVED** [review]
Just two minor comments :rocket:

File: mithril-aggregator/src/dependency_injection/builder.rs (hunk 1 above)
Comment (jpraynaud) [reply mithril-aggregator/src/dependency_injection/builder.rs]: Done :heavy_check_mark:

File: mithril-signer/src/runtime/signer_services.rs (hunk 2 above)
Comment (jpraynaud) [reply mithril-signer/src/runtime/signer_services.rs]: Done :heavy_check_mark:

**Review by sfauvel — APPROVED** [review]

**Review by dlachaumepalo — APPROVED** [review]

**Review by Alenar — APPROVED** [review]
