### PR TITLE
fix: add timeout to Pallas `chainsync` calls in Pallas chain reader

### LINKED ISSUE #3050: Cardano blocks and transaction import stalled in `dev` aggregators
## Why

On `dev-mainnet`, the aggregator state machine is healthy but the blocks and transactions import is stuck, while the signer import succeeds normally (running Cardano `10.6.2`):

```bash
sqlite3 -table data/mainnet/mithril-aggregator/mithril/stores/cardano-transaction.sqlite3 
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select * from cardano_block order by rowid desc limit 5;
+------------------------------------------------------------------+--------------+-------------+
|                            block_hash                            | block_number | slot_number |
+------------------------------------------------------------------+--------------+-------------+
| 6ef18b443f592f18cd31059311b8bb20c823fb28c70d8cc7c0fee81a9769a605 | 13079034     | 180319545   |
| 67d200df2a6fda59091397153f43d4559696f259d583daef3961ae205bec66b4 | 13079033     | 180319508   |
| 05d4327bd97f01827bd13bb10a95f22771c84be733d0c5e461247cae4338f3ec | 13079032     | 180319498   |
| f184f519351444b0b203bb765c14f736a23a033d3e3061ac9ea8947a57dc8094 | 13079031     | 180319487   |
| cd0f7ba4a6c12a8204d6a0dd7d980773cd0deedcf590b69bc51962550448cfd1 | 13079030     | 180319473   |
+------------------------------------------------------------------+--------------+-------------+

```

```bash
sqlite3 -table data/mainnet/mithril-signer-1/mithril/stores/cardano-transaction.sqlite3 
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select * from cardano_block order by rowid desc limit 5;
+------------------------------------------------------------------+--------------+-------------+
|                            block_hash                            | block_number | slot_number |
+------------------------------------------------------------------+--------------+-------------+
| 81d46cca959c5f59069021e9baef8422e23fbc096ca416b62ca4b8f2d160ab3d | 13084829     | 180437367   |
| 157d1beb1bad6b002802174d99521a3a026e000422523d6ec0e2ad2409f21c03 | 13084828     | 180437362   |
| ec095dfb2744d399e4e595fdc225ac9ed0c263a4ea2b085cb4a6c17f9ae0c36f | 13084827     | 180437360   |
| 566d595729bc8c497b312c6c50dcdb677b825e7be59df881c2c2511e057769e4 | 13084826     | 180437349   |
| 58cf8405336351aed3ec9819d70815e79527ccf1781330fd0bbf6cb1a8d905a3 | 13084825     | 180437347   |
+------------------------------------------------------------------+--------------+-------------+

```

The same behavior occurs on the `dev-follower-preview` aggregator  (running Cardano `10.5.3`).

After investigation, we strongly suspect a connection to the Cardano node made by Pallas being stuck. When the Cardano node stops responding without closing the socket, these calls hang indefinitely. This keeps the preloader in an incomplete state and prevents it from ever releasing the `SignedEntityTypeLock`, blocking signing and artifact creation for `CardanoTransactions` and `CardanoBlocksTransactions`.

## What
Investigate and fix the source of the problem.

## How
- [x] Investigate the problem
- [x] Create a fix:
  - [x] Add a `tokio::time::timeout` to `find_intersect_point` in the Pallas chain reader
  - [x] Add a `tokio::time::timeout` to `get_next_chain_block` in the Pallas chain reader
  - [x] On timeout, call `drop_client()` to force reconnection on next use
  - [x] On timeout, log a specific warning message

### PR DESCRIPTION
**Pull request by jpraynaud**
## Content

This PR adds **proper timeout handling to the Pallas `chainsync` calls in the chain reader which avoids having these calls stuck indefinitely**.

## Pre-submit checklist

- Branch
  - [x] Tests are provided (if possible)
  - [x] Crates versions are updated (if relevant)
  - [x] Commit sequence broadly makes sense
  - [x] Key commits have useful messages
- PR
  - [x] All check jobs of the CI have succeeded
  - [x] Self-reviewed the diff
  - [x] Useful pull request description
  - [x] Reviewer requested

## Issue(s)
Closes #3050

### CODE REVIEW

File: internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs [hunk 1]
```diff
@@ -74,12 +99,39 @@ impl PallasChainReader {
...
+                chainsync.find_intersect(vec![point.to_owned().into()]),
+            )
+            .await;
+            match result {
+                Ok(Ok(_)) => {}
+                Ok(Err(err)) => {
+                    self.drop_client();
+
+                    return Err(anyhow::Error::new(err)
+                        .context("PallasChainReader failed to find intersect point"));
```
Comment (Alenar) [inline internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs]: Can't you use `anyhow::bail!` here ? _(Same comment for the other `return Error(anyhow(...))`)_
```suggestion
                    anyhow::bail!(err).context("PallasChainReader failed to find intersect point"));
```

File: internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs [hunk 2]
```diff
@@ -32,16 +38,35 @@ impl PallasChainReader {
...
+            NodeClient::connect(&self.socket, magic),
+        )
+        .await
+        .map_err(|_| {
+            warn!(
+                self.logger,
+                "Timeout elapsed while connecting to the Cardano node";
+                "timeout" => ?self.chainsync_timeout,
+                "socket" => self.socket.display().to_string()
+            );
```
Comment (Alenar) [inline internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs:64]: _same comment for other new logs_

Rustfmt don't work for logs macro when we use a `;`, meaning you can format it as you want, for case like this with few additional values I shorten it by grouping together the logger and the message, plus grouping the values.
```suggestion
            warn!(
                self.logger, "Timeout elapsed while connecting to the Cardano node";
                "timeout" => ?self.chainsync_timeout, "socket" => self.socket.display().to_string()
            );
```

File: internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs [hunk 3]
```diff
@@ -74,12 +99,27 @@ impl PallasChainReader {
...
+            .map_err(|_| {
+                warn!(
+                    logger,
+                    "Timeout elapsed while finding intersect point";
+                    "timeout" => ?chainsync_timeout,
+                    "point" => ?point
+                );
+                anyhow::anyhow!("PallasChainReader timed out finding intersect point")
+            })?
+            .with_context(|| "PallasChainReader failed to find intersect point")?;
```
[the remark this answers is not in the document]
Comment (jpraynaud) [reply internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs]: Fixed

[the remark this answers is not in the document]
Comment (jpraynaud) [reply internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs]: Fixed

**Review by Alenar — APPROVED** [review]
LGTM

File: internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs (hunk 2 above)
Comment (jpraynaud) [reply internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs:64]: Fixed

File: internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs (hunk 1 above)
Comment (jpraynaud) [reply internal/cardano-node/mithril-cardano-node-chain/src/chain_reader/pallas_chain_reader.rs]: Fixed
